### ISSUE TITLE
Update version of Gobblin

### ISSUE THREAD

**Issue by brunowego** [Gradiant/dockerized-gobblin#1]
Hi, I want to submit a update version of Gobblin, can you create a develop/master branch to submit it?

**Comment by cgiraldo** [comment]
I see that you want gobblin-0.14.0.
I have created a gobblin-0.14.0 branch.
Can you make a PR on that branch?

**Comment by brunowego** [comment]
Sorry for the delay, I am behind a network with proxy. I will submit this after some tests.

**Comment by brunowego** [comment]
Thanks @cgiraldo, can you put a tag here for 0.14.0? https://hub.docker.com/r/gradiant/gobblin/tags

**Comment by cgiraldo** [comment]
dockerhub builds are automated. It takes some time to finish docker image build.
Take a look to: [https://hub.docker.com/r/gradiant/gobblin/builds](https://hub.docker.com/r/gradiant/gobblin/builds) to see the current build status.
